name: szakmasztar
description: IT Vizsga - Hálózati kérdések kvíz app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json
